-- Choices are revocable owner interaction state, never independent authorization.
ALTER TABLE kestri.conversations
    ADD COLUMN IF NOT EXISTS memory_choice jsonb;

-- Presentation is generated by the application; model answers remain plain text.
ALTER TABLE kestri.outbox
    ADD COLUMN IF NOT EXISTS presentation jsonb;

INSERT INTO kestri.migrations (version) VALUES (10) ON CONFLICT DO NOTHING;
